# mysql
sqlinj_db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_USER: "foo"
    MYSQL_PASSWORD: "bar"
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
sqlinj_app:
  build: ./sqlinjection
  ports:
    - "8686:80"
  links:
    - sqlinj_db:db
myadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8687:80"
  environment:
    PMA_HOST: "db"
  links:
    - sqlinj_db:db